[build-system]
requires = ["scikit-build-core~=0.12"]
build-backend = "scikit_build_core.build"

[project]
name = "unit-compiler"
version = "0.1.0-dev"
description = "Stack-based compiler backend."
requires-python = ">=3.14"
authors = [
    { name = "Peter Bierma", email = "peter@python.org" },
]
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
]

[tool.scikit-build]
cmake.args = ["-DUNIT_BUILD_PYTHON=ON"]
wheel.packages = ["python/unit"]
cmake.build-type = "Debug"
