#ifndef UNIT_ELF_LOCAL_H
#define UNIT_ELF_LOCAL_H

#define ELF_CLASS_64 2
#define ELF_DATA_LITTLE_ENDIAN 1
#define ELF_VERSION_CURRENT 1

#define ELF_TYPE_RELOCATABLE 1
#define ELF_MACHINE_AMD64 62

#define ELF_SECTION_TYPE_PROGRAM_DATA 1
#define ELF_SECTION_TYPE_SYMBOL_TABLE 2
#define ELF_SECTION_TYPE_STRING_TABLE 3
#define ELF_SECTION_TYPE_RELA 4

#define ELF_SECTION_FLAG_ALLOC 0x02
#define ELF_SECTION_FLAG_EXECUTABLE 0x04
#define ELF_SECTION_FLAG_INFO_LINK 0x40

#define ELF_SYMBOL_BINDING_LOCAL 0
#define ELF_SYMBOL_BINDING_GLOBAL 1

#define ELF_SYMBOL_TYPE_NONE 0
#define ELF_SYMBOL_TYPE_FUNCTION 2
#define ELF_SYMBOL_TYPE_SECTION 3

#define ELF_SECTION_UNDEFINED 0

#define ELF_RELOCATION_AMD64_PC32 2
#define ELF_RELOCATION_AMD64_PLT32 4

#define ELF_FILE_HEADER_SIZE 64
#define ELF_SECTION_HEADER_SIZE 64
#define ELF_RELOCATION_SIZE 24
#define ELF_SYMBOL_SIZE 24

#endif
